### ISSUE TITLE
Setting up differential drive base with MoveIT2

### ISSUE THREAD

**Issue by Giovadess** [hello-robot/stretch_ros2#54]
Hello!
Referring to the tutorial (https://moveit.picknik.ai/humble/doc/examples/mobile_base_arm/mobile_base_arm_tutorial.html) I thought this would be the right place to ask this question.

I am trying to expand what explained to a four wheeled differential drive robot.
I followed all the steps, and as a result I have the planner working in rviz, the controller is identified and so on.
The problem comes in the execution, when I click on execute trajectory in Rviz it fails. 

I figure out the moveit2 controller manager.
This is the configuration for the position virtual Joint

    <group name="position">
        <joint name="position" />
        
    </group>

    <group name="arm_group">
        <link name="arm_link_1" />
        <joint name="arm_joint_base" />
        <joint name="arm_joint_1" />
    </group>

    <group name="mobile_base_arm">
        <group name="position" />
        <group name="arm_group" />
    </group>

    <virtual_joint name="position" type="planar" parent_frame="odom" child_link="base_footprint"/>
    <joint_property joint_name="position" property_name="motion_model" value="diff_drive" />
    <joint_property joint_name="position" property_name="min_translational_distance" value="0.01" />
    <joint_property joint_name="position" property_name="angular_distance_weight" value="0.5" />

I have setup my mobile base with a diff-drive controller from ros2 but it doesn't work. I do also have a follow joint traj controller but it does not work as well.
I was looking into the stretch repositories for details about the controller for the base but could not find what it uses, do you rely on the ros2_control package or do you use your custom controller for the base?
If so would it be possible to use this same set up with a standard differential drive controller or do I need a way around that?

I also noticed that the stretch urdf does not contain any reference to this joint called position but it only has the two wheels and the caster one, how does the robot understand that it has to move or to send a command to the wheels when the position joint is actuated?
I am using ros2 galactic on Ubuntu 20.04.

Thanks.

![image](https://github.com/hello-robot/stretch_ros2/assets/117512744/f5980a43-f3ce-4fd6-8c2e-d77a5e7c77c8)

**Comment by hello-chintan** [comment]
Hey @Giovadess,

Thank you for reaching out! Since your issue is not specific to a Stretch robot, this might not be the right forum. I recommend redirecting questions specific to your setup to [MoveIt 2 Issues](https://github.com/ros-planning/moveit2/issues).

> do you rely on the ros2_control package or do you use your custom controller for the base?

We do not use ros2_control. Instead, we rely on custom controllers defined in [stretch_body](https://github.com/hello-robot/stretch_body) which is the Python SDK for Stretch. The ROS stack builds on top of stretch_body to interact with the firmware.

> I also noticed that the stretch urdf does not contain any reference to this joint called position but it only has the two wheels and the caster one, how does the robot understand that it has to move or to send a command to the wheels when the position joint is actuated?

The stretch_description.srdf file defines a virtual joint named 'position' with a 'diff_drive' motion model that allows the MoveIt 2 planner to generate a plan for the mobile_base. This is a planar multi-DOF joint that can be controlled based on SE2 co-ordinates (x, y, theta).

The generated plan is executed by the [joint trajectory server](https://github.com/hello-robot/stretch_ros2/blob/humble/stretch_core/stretch_core/trajectory_components.py#L114) which addresses the 'position' joint commands to the [robot.base](https://github.com/hello-robot/stretch_body/blob/master/body/stretch_body/base.py) class in the stretch_body Python SDK.

The [diff drive controller](https://github.com/hello-robot/stretch_body/blob/master/body/stretch_body/trajectories.py#L489) defined in stretch_body then converts the generated trajectory into appropriate motor velocities to execute the mobile base motion plan.

Hope that helps!

Best,
Chintan Desai
